name: checkov
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Test with Checkov 
      id: Checkov
      uses: bridgecrewio/bridgecrew-action@master
      with:
        directory: terraform/
